"""
NextGen Rule Recommendation Engine Powered by Generative AI

This module provides intelligent, context-aware suggestions for rule creation and optimization
in fraud detection and risk management systems.
"""

import json
import logging
import random
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple, Any
from dataclasses import dataclass, asdict
from enum import Enum
import hashlib


# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class RuleType(Enum):
    """Types of rules that can be recommended"""
    FRAUD_DETECTION = "fraud_detection"
    RISK_ASSESSMENT = "risk_assessment"
    TRANSACTION_MONITORING = "transaction_monitoring"
    VELOCITY_CHECK = "velocity_check"
    BEHAVIORAL_ANALYSIS = "behavioral_analysis"
    GEOGRAPHIC_RESTRICTION = "geographic_restriction"


class RiskLevel(Enum):
    """Risk levels for rule recommendations"""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class TransactionContext:
    """Context information for a transaction"""
    transaction_id: str
    user_id: str
    amount: float
    currency: str
    merchant_category: str
    location: str
    timestamp: datetime
    payment_method: str
    device_fingerprint: str
    ip_address: str
    
    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data['timestamp'] = self.timestamp.isoformat()
        return data


@dataclass
class RuleRecommendation:
    """A rule recommendation generated by the AI engine"""
    rule_id: str
    rule_type: RuleType
    name: str
    description: str
    conditions: Dict[str, Any]
    actions: List[str]
    confidence_score: float
    risk_level: RiskLevel
    estimated_impact: Dict[str, float]
    reasoning: str
    created_at: datetime
    
    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data['rule_type'] = self.rule_type.value
        data['risk_level'] = self.risk_level.value
        data['created_at'] = self.created_at.isoformat()
        return data


@dataclass
class HistoricalPattern:
    """Historical pattern data for AI analysis"""
    pattern_id: str
    pattern_type: str
    frequency: int
    success_rate: float
    false_positive_rate: float
    last_seen: datetime
    attributes: Dict[str, Any]


class AIRuleEngine:
    """Core AI-powered rule recommendation engine"""
    
    def __init__(self):
        self.historical_patterns: List[HistoricalPattern] = []
        self.active_rules: List[RuleRecommendation] = []
        self.performance_metrics: Dict[str, float] = {}
        self._initialize_baseline_patterns()
    
    def _initialize_baseline_patterns(self):
        """Initialize with baseline fraud patterns"""
        baseline_patterns = [
            {
                "pattern_type": "high_velocity_transactions",
                "frequency": 150,
                "success_rate": 0.85,
                "false_positive_rate": 0.12,
                "attributes": {"time_window": "5_minutes", "threshold": 5}
            },
            {
                "pattern_type": "unusual_location",
                "frequency": 89,
                "success_rate": 0.78,
                "false_positive_rate": 0.08,
                "attributes": {"distance_threshold": "500_miles", "time_threshold": "2_hours"}
            },
            {
                "pattern_type": "amount_anomaly",
                "frequency": 234,
                "success_rate": 0.92,
                "false_positive_rate": 0.15,
                "attributes": {"deviation_multiplier": 3.5, "baseline_period": "30_days"}
            }
        ]
        
        for i, pattern_data in enumerate(baseline_patterns):
            pattern = HistoricalPattern(
                pattern_id=f"baseline_{i}",
                pattern_type=pattern_data["pattern_type"],
                frequency=pattern_data["frequency"],
                success_rate=pattern_data["success_rate"],
                false_positive_rate=pattern_data["false_positive_rate"],
                last_seen=datetime.now() - timedelta(days=random.randint(1, 30)),
                attributes=pattern_data["attributes"]
            )
            self.historical_patterns.append(pattern)
    
    def analyze_transaction_context(self, context: TransactionContext) -> Dict[str, Any]:
        """Analyze transaction context for risk indicators"""
        risk_indicators = {
            "velocity_risk": self._calculate_velocity_risk(context),
            "amount_risk": self._calculate_amount_risk(context),
            "location_risk": self._calculate_location_risk(context),
            "device_risk": self._calculate_device_risk(context),
            "behavioral_risk": self._calculate_behavioral_risk(context)
        }
        
        overall_risk_score = sum(risk_indicators.values()) / len(risk_indicators)
        risk_indicators["overall_risk_score"] = overall_risk_score
        
        return risk_indicators
    
    def _calculate_velocity_risk(self, context: TransactionContext) -> float:
        """Calculate velocity-based risk score"""
        # Simulate velocity analysis
        base_risk = random.uniform(0.1, 0.4)
        if context.amount > 1000:
            base_risk += 0.2
        return min(base_risk, 1.0)
    
    def _calculate_amount_risk(self, context: TransactionContext) -> float:
        """Calculate amount-based risk score"""
        # Simulate amount anomaly detection
        if context.amount > 5000:
            return random.uniform(0.6, 0.9)
        elif context.amount > 1000:
            return random.uniform(0.3, 0.6)
        return random.uniform(0.1, 0.3)
    
    def _calculate_location_risk(self, context: TransactionContext) -> float:
        """Calculate location-based risk score"""
        # Simulate geographic risk analysis
        high_risk_locations = ["Unknown", "High-Risk-Country"]
        if any(loc in context.location for loc in high_risk_locations):
            return random.uniform(0.7, 0.95)
        return random.uniform(0.1, 0.4)
    
    def _calculate_device_risk(self, context: TransactionContext) -> float:
        """Calculate device-based risk score"""
        # Simulate device fingerprinting analysis
        if "unknown" in context.device_fingerprint.lower():
            return random.uniform(0.5, 0.8)
        return random.uniform(0.1, 0.3)
    
    def _calculate_behavioral_risk(self, context: TransactionContext) -> float:
        """Calculate behavioral risk score"""
        # Simulate behavioral analysis
        return random.uniform(0.2, 0.6)
    
    def generate_rule_recommendations(self, context: TransactionContext, 
                                    max_recommendations: int = 5) -> List[RuleRecommendation]:
        """Generate AI-powered rule recommendations based on transaction context"""
        risk_analysis = self.analyze_transaction_context(context)
        recommendations = []
        
        # Generate recommendations based on risk indicators
        if risk_analysis["velocity_risk"] > 0.6:
            recommendations.append(self._create_velocity_rule(context, risk_analysis))
        
        if risk_analysis["amount_risk"] > 0.7:
            recommendations.append(self._create_amount_threshold_rule(context, risk_analysis))
        
        if risk_analysis["location_risk"] > 0.6:
            recommendations.append(self._create_geographic_rule(context, risk_analysis))
        
        if risk_analysis["device_risk"] > 0.5:
            recommendations.append(self._create_device_verification_rule(context, risk_analysis))
        
        if risk_analysis["behavioral_risk"] > 0.5:
            recommendations.append(self._create_behavioral_rule(context, risk_analysis))
        
        # Sort by confidence score and return top recommendations
        recommendations.sort(key=lambda x: x.confidence_score, reverse=True)
        return recommendations[:max_recommendations]
    
    def _create_velocity_rule(self, context: TransactionContext, 
                            risk_analysis: Dict[str, Any]) -> RuleRecommendation:
        """Create a velocity-based rule recommendation"""
        rule_id = self._generate_rule_id("velocity", context)
        
        return RuleRecommendation(
            rule_id=rule_id,
            rule_type=RuleType.VELOCITY_CHECK,
            name=f"High Velocity Transaction Rule - {context.user_id}",
            description="Detect and flag high-velocity transaction patterns that may indicate fraud",
            conditions={
                "transaction_count": {"operator": ">", "value": 5, "time_window": "5_minutes"},
                "user_id": context.user_id,
                "amount_threshold": {"operator": ">", "value": 100}
            },
            actions=["flag_transaction", "require_additional_verification", "notify_risk_team"],
            confidence_score=0.85 + (risk_analysis["velocity_risk"] * 0.15),
            risk_level=RiskLevel.HIGH if risk_analysis["velocity_risk"] > 0.8 else RiskLevel.MEDIUM,
            estimated_impact={
                "fraud_prevention": 0.78,
                "false_positive_rate": 0.12,
                "processing_delay": 2.5
            },
            reasoning=f"High velocity risk detected ({risk_analysis['velocity_risk']:.2f}). "
                     f"User {context.user_id} showing unusual transaction frequency patterns.",
            created_at=datetime.now()
        )
    
    def _create_amount_threshold_rule(self, context: TransactionContext, 
                                    risk_analysis: Dict[str, Any]) -> RuleRecommendation:
        """Create an amount-based rule recommendation"""
        rule_id = self._generate_rule_id("amount", context)
        threshold = max(context.amount * 0.8, 1000)
        
        return RuleRecommendation(
            rule_id=rule_id,
            rule_type=RuleType.FRAUD_DETECTION,
            name=f"Amount Anomaly Detection Rule - {context.currency}",
            description="Flag transactions with amounts significantly above user's normal spending pattern",
            conditions={
                "amount": {"operator": ">", "value": threshold},
                "currency": context.currency,
                "deviation_from_average": {"operator": ">", "value": 3.0}
            },
            actions=["flag_transaction", "require_manual_review", "send_user_notification"],
            confidence_score=0.82 + (risk_analysis["amount_risk"] * 0.18),
            risk_level=RiskLevel.HIGH if context.amount > 10000 else RiskLevel.MEDIUM,
            estimated_impact={
                "fraud_prevention": 0.85,
                "false_positive_rate": 0.18,
                "processing_delay": 1.8
            },
            reasoning=f"Amount anomaly detected ({risk_analysis['amount_risk']:.2f}). "
                     f"Transaction amount ${context.amount} significantly exceeds normal patterns.",
            created_at=datetime.now()
        )
    
    def _create_geographic_rule(self, context: TransactionContext, 
                              risk_analysis: Dict[str, Any]) -> RuleRecommendation:
        """Create a geographic-based rule recommendation"""
        rule_id = self._generate_rule_id("geographic", context)
        
        return RuleRecommendation(
            rule_id=rule_id,
            rule_type=RuleType.GEOGRAPHIC_RESTRICTION,
            name=f"Geographic Anomaly Rule - {context.location}",
            description="Detect transactions from unusual or high-risk geographic locations",
            conditions={
                "location": {"operator": "in", "value": ["high_risk_countries", "unusual_locations"]},
                "distance_from_last_transaction": {"operator": ">", "value": "500_miles"},
                "time_since_last_transaction": {"operator": "<", "value": "2_hours"}
            },
            actions=["flag_transaction", "require_location_verification", "temporary_hold"],
            confidence_score=0.79 + (risk_analysis["location_risk"] * 0.21),
            risk_level=RiskLevel.HIGH if risk_analysis["location_risk"] > 0.8 else RiskLevel.MEDIUM,
            estimated_impact={
                "fraud_prevention": 0.72,
                "false_positive_rate": 0.08,
                "processing_delay": 3.2
            },
            reasoning=f"Geographic risk detected ({risk_analysis['location_risk']:.2f}). "
                     f"Transaction from {context.location} shows unusual location pattern.",
            created_at=datetime.now()
        )
    
    def _create_device_verification_rule(self, context: TransactionContext, 
                                       risk_analysis: Dict[str, Any]) -> RuleRecommendation:
        """Create a device verification rule recommendation"""
        rule_id = self._generate_rule_id("device", context)
        
        return RuleRecommendation(
            rule_id=rule_id,
            rule_type=RuleType.BEHAVIORAL_ANALYSIS,
            name=f"Device Verification Rule - {context.device_fingerprint[:8]}",
            description="Verify transactions from unrecognized or suspicious devices",
            conditions={
                "device_fingerprint": {"operator": "not_in", "value": "known_devices"},
                "device_risk_score": {"operator": ">", "value": 0.6},
                "first_time_device": True
            },
            actions=["require_device_verification", "send_sms_code", "flag_for_review"],
            confidence_score=0.76 + (risk_analysis["device_risk"] * 0.24),
            risk_level=RiskLevel.MEDIUM,
            estimated_impact={
                "fraud_prevention": 0.68,
                "false_positive_rate": 0.22,
                "processing_delay": 4.1
            },
            reasoning=f"Device risk detected ({risk_analysis['device_risk']:.2f}). "
                     f"Unrecognized device fingerprint requires additional verification.",
            created_at=datetime.now()
        )
    
    def _create_behavioral_rule(self, context: TransactionContext, 
                              risk_analysis: Dict[str, Any]) -> RuleRecommendation:
        """Create a behavioral analysis rule recommendation"""
        rule_id = self._generate_rule_id("behavioral", context)
        
        return RuleRecommendation(
            rule_id=rule_id,
            rule_type=RuleType.BEHAVIORAL_ANALYSIS,
            name=f"Behavioral Anomaly Rule - {context.user_id}",
            description="Detect behavioral patterns that deviate from user's normal activity",
            conditions={
                "transaction_time": {"operator": "outside", "value": "normal_hours"},
                "merchant_category": {"operator": "not_in", "value": "frequent_categories"},
                "behavioral_score": {"operator": ">", "value": 0.7}
            },
            actions=["flag_transaction", "behavioral_analysis", "user_verification"],
            confidence_score=0.73 + (risk_analysis["behavioral_risk"] * 0.27),
            risk_level=RiskLevel.MEDIUM,
            estimated_impact={
                "fraud_prevention": 0.65,
                "false_positive_rate": 0.25,
                "processing_delay": 2.8
            },
            reasoning=f"Behavioral anomaly detected ({risk_analysis['behavioral_risk']:.2f}). "
                     f"Transaction pattern deviates from user's normal behavior.",
            created_at=datetime.now()
        )
    
    def _generate_rule_id(self, rule_type: str, context: TransactionContext) -> str:
        """Generate a unique rule ID"""
        data = f"{rule_type}_{context.user_id}_{context.timestamp.isoformat()}"
        return f"rule_{hashlib.md5(data.encode()).hexdigest()[:8]}"
    
    def optimize_existing_rules(self, performance_data: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Optimize existing rules based on performance data"""
        optimizations = []
        
        for rule in self.active_rules:
            rule_performance = performance_data.get(rule.rule_id, {})
            
            if rule_performance.get("false_positive_rate", 0) > 0.3:
                optimizations.append({
                    "rule_id": rule.rule_id,
                    "optimization_type": "reduce_sensitivity",
                    "current_fp_rate": rule_performance["false_positive_rate"],
                    "suggested_changes": {
                        "increase_thresholds": True,
                        "add_whitelist_conditions": True
                    },
                    "expected_improvement": 0.15
                })
            
            if rule_performance.get("detection_rate", 0) < 0.5:
                optimizations.append({
                    "rule_id": rule.rule_id,
                    "optimization_type": "increase_sensitivity",
                    "current_detection_rate": rule_performance["detection_rate"],
                    "suggested_changes": {
                        "decrease_thresholds": True,
                        "add_additional_conditions": True
                    },
                    "expected_improvement": 0.20
                })
        
        return optimizations
    
    def export_recommendations(self, recommendations: List[RuleRecommendation], 
                             filename: str = None) -> str:
        """Export rule recommendations to JSON file"""
        if filename is None:
            filename = f"rule_recommendations_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        
        export_data = {
            "generated_at": datetime.now().isoformat(),
            "total_recommendations": len(recommendations),
            "recommendations": [rec.to_dict() for rec in recommendations]
        }
        
        with open(filename, 'w') as f:
            json.dump(export_data, f, indent=2)
        
        logger.info(f"Exported {len(recommendations)} recommendations to {filename}")
        return filename


class RuleRecommendationAPI:
    """API interface for the rule recommendation engine"""
    
    def __init__(self):
        self.engine = AIRuleEngine()
    
    def get_recommendations(self, transaction_data: Dict[str, Any]) -> Dict[str, Any]:
        """Get rule recommendations for a transaction"""
        try:
            # Convert transaction data to context object
            context = TransactionContext(
                transaction_id=transaction_data["transaction_id"],
                user_id=transaction_data["user_id"],
                amount=float(transaction_data["amount"]),
                currency=transaction_data.get("currency", "USD"),
                merchant_category=transaction_data.get("merchant_category", "unknown"),
                location=transaction_data.get("location", "unknown"),
                timestamp=datetime.fromisoformat(transaction_data.get("timestamp", datetime.now().isoformat())),
                payment_method=transaction_data.get("payment_method", "card"),
                device_fingerprint=transaction_data.get("device_fingerprint", "unknown"),
                ip_address=transaction_data.get("ip_address", "0.0.0.0")
            )
            
            # Generate recommendations
            recommendations = self.engine.generate_rule_recommendations(context)
            
            return {
                "status": "success",
                "transaction_id": context.transaction_id,
                "recommendations_count": len(recommendations),
                "recommendations": [rec.to_dict() for rec in recommendations],
                "risk_analysis": self.engine.analyze_transaction_context(context)
            }
            
        except Exception as e:
            logger.error(f"Error generating recommendations: {str(e)}")
            return {
                "status": "error",
                "error_message": str(e),
                "recommendations": []
            }


# Example usage and testing
def main():
    """Example usage of the NextGen Rule Recommendation Engine"""
    
    # Initialize the API
    api = RuleRecommendationAPI()
    
    # Example transaction data
    sample_transaction = {
        "transaction_id": "txn_12345",
        "user_id": "user_67890",
        "amount": 2500.00,
        "currency": "USD",
        "merchant_category": "electronics",
        "location": "New York, NY",
        "timestamp": datetime.now().isoformat(),
        "payment_method": "credit_card",
        "device_fingerprint": "unknown_device_abc123",
        "ip_address": "192.168.1.100"
    }
    
    # Get recommendations
    result = api.get_recommendations(sample_transaction)
    
    # Print results
    print("=== NextGen Rule Recommendation Engine Results ===")
    print(f"Status: {result['status']}")
    print(f"Transaction ID: {result.get('transaction_id', 'N/A')}")
    print(f"Number of Recommendations: {result.get('recommendations_count', 0)}")
    
    if result.get('recommendations'):
        print("\n=== Recommended Rules ===")
        for i, rec in enumerate(result['recommendations'], 1):
            print(f"\n{i}. {rec['name']}")
            print(f"   Type: {rec['rule_type']}")
            print(f"   Risk Level: {rec['risk_level']}")
            print(f"   Confidence: {rec['confidence_score']:.2f}")
            print(f"   Description: {rec['description']}")
            print(f"   Reasoning: {rec['reasoning']}")
    
    # Export recommendations
    if result.get('recommendations'):
        recommendations = [RuleRecommendation(**{
            **rec,
            'rule_type': RuleType(rec['rule_type']),
            'risk_level': RiskLevel(rec['risk_level']),
            'created_at': datetime.fromisoformat(rec['created_at'])
        }) for rec in result['recommendations']]
        
        filename = api.engine.export_recommendations(recommendations)
        print(f"\n=== Recommendations exported to: {filename} ===")


if __name__ == "__main__":
    main()
